replicas: 1

image: 
  repository: ibmcom/icp-cert-policy-controller
  tag: 4.1.0
  pullPolicy: IfNotPresent

args:
  frequency:
  verbosity: 0
  defaultDuration:

securityContext:
  pod:
    runAsUser: 10000
    runAsNonRoot: true    
  container:
    allowPrivilegeEscalation: false
    runAsUser: 10000
    readOnlyRootFilesystem: false
    runAsNonRoot: true

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists

podDnsPolicy: "ClusterFirstWithHostNet"
