apiVersion: v1
appVersion: 0.10.0
description: Create custom resource definitions needed by IBM Cloud Private cert-manager
keywords:
- amd64
- ppc64le
- OpenSource
- ICP
- IcpClusterResource
- Security
- cert-manager
- Development
- IBM Cloud Private
- Beta
- Commercial
kubeVersion: '>=1.9.0-0'
name: ibm-cert-manager-crd
tillerVersion: '>=2.7.0'
version: 3.4.0
