# Copyright Contributors to the Open Cluster Management project

# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "search.fullname" . }}
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    component: "search"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    mcm.ibm.com/globalview: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "search.name" . }}
      component: "search"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: {{ template "search.name" . }}
        component: "search"
        controller: "operator"
        release: {{ .Release.Name }}
        chart: {{ template "search.chart" . }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ template "search.fullname" . }}
      containers:
      - name: lease-controller
        image: "{{ .Values.global.imageOverrides.klusterlet_addon_lease_controller }}"
        command:
        - klusterlet-addon-lease-controller
        args:
        - -lease-name
        - {{ .Values.leaseController.name }}
        - -lease-namespace
        - "{{ .Values.clusterNamespace }}"
        - -hub-kubeconfig-secret
        - {{ .Values.hubKubeconfigSecret }}
        - -lease-duration
        - "60"
        - -startup-delay
        - "10"
        resources:
{{ toYaml .Values.leaseController.resources | indent 10 }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      {{- if not (or (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1/MultiClusterHub") (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1beta1/MultiClusterHub")) }}
      - name: collector
        image: "{{ .Values.global.imageOverrides.search_collector }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: CLUSTER_NAME
          value: "{{ .Values.clusterName }}"
        - name: CLUSTER_NAMESPACE
          value: "{{ .Values.clusterNamespace }}"
        - name: HUB_CONFIG
          value: /hubconfig/kubeconfig
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe: null
        readinessProbe: null
        volumeMounts:
        - name: hub-config
          mountPath: /hubconfig
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .Values.hubKubeconfigSecret }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
{{- end }}
