replicas: 1

image: 
  repository: ibmcom/icp-cert-policy-controller
  tag: 3.3.0
  pullPolicy: IfNotPresent

args:
  frequency: 60
  verbosity: 0
  defaultDuration:

securityContext:
  pod:
    runAsUser: 10000
    runAsNonRoot: true    
  container:
    allowPrivilegeEscalation: false
    runAsUser: 10000
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    privileged: false

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists

podDnsPolicy: "ClusterFirstWithHostNet"

serviceAccount:
  create: false
  name: "default"
