# Copyright Contributors to the Open Cluster Management project

# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.

{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "policy.fullname" . }}-framework
  labels:
    app: {{ template "policy.name" . }}-framework
    chart: {{ template "policy.chart" . }}
    component: "governance"
    release: {{ .Release.Name }}
    controller: "operator"
    heritage: {{ .Release.Service }}
    hubKubeconfigSecret: {{ .Values.hubKubeconfigSecret }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "policy.name" . }}-framework
      component: "governance"
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: {{ template "policy.name" . }}-framework
        component: "governance"
        controller: "operator"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "policy.chart" . }}
    spec:
      serviceAccountName: {{ template "policy.fullname" . }}
      containers:
      {{- if not (or (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1/MultiClusterHub") (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1beta1/MultiClusterHub")) }}
      - name: spec-sync
        image: "{{ .Values.global.imageOverrides.governance_policy_spec_sync }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        command: ["governance-policy-spec-sync"]
        env:
          - name: WATCH_NAMESPACE
            value: "{{ .Values.clusterNamespace }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "governance-policy-spec-sync"
          {{- if .Values.global.proxyConfig.HTTP_PROXY }}
          - name: HTTP_PROXY
            value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
          - name: HTTPS_PROXY
            value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.NO_PROXY }}
          - name: NO_PROXY
            value: {{ .Values.global.proxyConfig.NO_PROXY }}
          {{- end }}
        args:
          - '--hub-cluster-configfile=/var/run/klusterlet/kubeconfig'
        livenessProbe: null
        readinessProbe: null
        volumeMounts:
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      {{- end }}
      - name: status-sync
        image: "{{ .Values.global.imageOverrides.governance_policy_status_sync }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        command: ["governance-policy-status-sync"]
        args:
          - '--enable-lease=true'
          - '--hub-cluster-configfile=/var/run/klusterlet/kubeconfig'
        env:
          - name: WATCH_NAMESPACE
            value: "{{ .Values.clusterNamespace }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "governance-policy-status-sync"
          {{- if (or (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1/MultiClusterHub") (.Capabilities.APIVersions.Has "operator.open-cluster-management.io/v1beta1/MultiClusterHub")) }}
          - name: ON_MULTICLUSTERHUB
            value: "true"
          {{- end }}
          {{- if .Values.global.proxyConfig.HTTP_PROXY }}
          - name: HTTP_PROXY
            value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
          - name: HTTPS_PROXY
            value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.NO_PROXY }}
          - name: NO_PROXY
            value: {{ .Values.global.proxyConfig.NO_PROXY }}
          {{- end }}
        livenessProbe: null
        readinessProbe: null
        volumeMounts:
          - name: klusterlet-config
            mountPath: /var/run/klusterlet
      - name: template-sync
        image: "{{ .Values.global.imageOverrides.governance_policy_template_sync }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        command: ["governance-policy-template-sync"]
        env:
          - name: WATCH_NAMESPACE
            value: "{{ .Values.clusterNamespace }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "governance-policy-template-sync"
          {{- if .Values.global.proxyConfig.HTTP_PROXY }}
          - name: HTTP_PROXY
            value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
          - name: HTTPS_PROXY
            value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
          {{- end }}
          {{- if .Values.global.proxyConfig.NO_PROXY }}
          - name: NO_PROXY
            value: {{ .Values.global.proxyConfig.NO_PROXY }}
          {{- end }}
        livenessProbe: null
        readinessProbe: null
      volumes:
        - name: klusterlet-config
          secret:
            secretName: {{ .Values.hubKubeconfigSecret }}
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
