apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "controller.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "controller.fullname" . }}
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "controller.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ include "controller.name" . }}
        app: {{ include "controller.name" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ include "controller.chart" . }}
    spec:
      hostPID: false
      hostIPC: false
      serviceAccount: {{ template "controller.serviceAccountName" . }}
      securityContext:
{{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }} 
        runAsUser: {{ .Values.securityContext.pod.runAsUser }}
{{- end }}
        runAsNonRoot: {{ .Values.securityContext.pod.runAsNonRoot }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --v={{ .Values.args.verbosity }}
        {{- if .Values.args.frequency }}
        - --update-frequency={{ .Values.args.frequency }}
        {{- end }}
        {{- if .Values.args.defaultDuration }}
        - --default-duration={{ .Values.args.defaultDuration }}
        {{- end }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pgrep cert-policy -l
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec echo start certificate-policy-controller"]
          initialDelaySeconds: 10
          timeoutSeconds: 2
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
          requests:
            memory: "150Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.container.allowPrivilegeEscalation }}
{{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }} 
          runAsUser: {{ .Values.securityContext.container.runAsUser }}
{{- end }}          
          readOnlyRootFilesystem: {{ .Values.securityContext.container.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.securityContext.container.runAsNonRoot }}
          privileged: {{ .Values.securityContext.container.privileged }}
          capabilities:
            drop:
            - ALL
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      hostNetwork: true
{{- if .Values.podDnsPolicy }}
      dnsPolicy: {{ .Values.podDnsPolicy }}
{{- end }}
