qualification:
  levelName: "ibm-cloud-pak"
  levelDescription: "IBM Cloud Pak"
  issueDate: ""
  duration: ""
  terms: ""
prereqs:
  security:
    kubernetes:
      podSecurityPolicy:
        name: ""
    openshift:
      securityContextConstraints:
        name: ""
    ibmCloudPrivate:
      installerRole:
        name: "ClusterAdministrator"  
  k8sDistros:
    kubernetes:
      semver: ">=1.12.4"
    ibmCloudPrivate:
      semver: ">=3.1.0"
    openshift:
      semver: ">=1.11.0"
