# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "iamPolicyController.fullname" . }}
  labels:
    app: {{ template "iamPolicyController.fullname" . }}
    chart: {{ template "iamPolicyController.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "iamPolicyController.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "iamPolicyController.name" . }}
        app: {{ template "iamPolicyController.fullname" . }}
        chart: {{ template "iamPolicyController.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "iamPolicyController.serviceAccount" . }}
      containers:
      - name: lease-controller
        image: "{{ .Values.global.imageOverrides.klusterlet_addon_lease_controller }}"
        command:
        - klusterlet-addon-lease-controller
        args:
        - -lease-name
        - {{ .Values.leaseController.name }}
        - -lease-namespace
        - "{{ .Values.clusterNamespace }}"
        - -hub-kubeconfig-secret
        - {{ .Values.hubKubeconfigSecret }}
        - -lease-duration
        - "60"
        - -startup-delay
        - "10"
        resources:
{{ toYaml .Values.leaseController.resources | indent 10 }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      - name: {{ template "iamPolicyController.name" . }}
        image: "{{ .Values.global.imageOverrides.iam_policy_controller }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        args:
        - --v={{ .Values.args.verbosity }}
        {{- if .Values.args.frequency }}
        - --update-frequency={{ .Values.args.frequency }}
        {{- end }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pgrep iam-policy -l
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec echo start iam-policy-controller"]
          initialDelaySeconds: 10
          timeoutSeconds: 2
        env:
        - name: WATCH_NAMESPACE
          value: "{{ .Values.clusterNamespace }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "iamPolicyController.fullname" . }}
        resources:
          limits:
            memory: "300Mi"
          requests:
            memory: "150Mi"
        securityContext:
          privileged: {{ .Values.securityContext.privileged }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          capabilities:
              drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
    {{- end }}
