# Copyright Contributors to the Open Cluster Management project

# Licensed Materials - Property of IBM
# IBM Confidential
# OCO Source Materials
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
org: open-cluster-management

enabled: true
hubKubeconfigSecret: null

clusterName: null
clusterNamespace: null

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi

nodeSelector: {}

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

logLevel: 5

postDeleteJobServiceAccount: null

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    governance_policy_spec_sync: quay.io/open-cluster-management/governance-policy-spec-sync:latest-dev
    governance_policy_status_sync: quay.io/open-cluster-management/governance-policy-status-sync:latest-dev
    governance_policy_template_sync: quay.io/open-cluster-management/governance-policy-template-sync:latest-dev
    config_policy_controller: quay.io/open-cluster-management/config-policy-controller:latest-dev
    klusterlet_addon_lease_controller: quay.io/open-cluster-management/klusterlet-addon-lease-controller:2.2.0