charts:
  - archive: file:ibm-cert-policy-controller-3.3.0.tgz
    repository-keys:
    - image.repository
images:
- image: "icp-cert-policy-controller:3.2.1"
  references:
  - pull-authorization:
      password:
        env: ARTIFACTORY_PASSWORD
      username:
        env: ARTIFACTORY_USERNAME
    pull-repository: icp-cert-policy-controller:3.2.1-amd64
    repository: icp-cert-policy-controller-amd64:3.2.1
    platform:
      os: linux
      architecture: amd64
  - pull-authorization:
      password:
        env: ARTIFACTORY_PASSWORD
      username:
        env: ARTIFACTORY_USERNAME
    pull-repository: icp-cert-policy-controller:3.2.1-ppc64le
    repository: icp-cert-policy-controller-ppc64le:3.2.1
    platform:
      os: linux
      architecture: ppc64le
  - pull-authorization:
      password:
        env: ARTIFACTORY_PASSWORD
      username:
        env: ARTIFACTORY_USERNAME
    pull-repository: icp-cert-policy-controller:3.2.1-s390x
    repository: icp-cert-policy-controller-s390x:3.2.1
    platform:
      os: linux
      architecture: s390x
